// alert("hello, world!");

// let message = 120;
// console.log(typeof message);

// let sum = 10 + 20;
// console.log(sum);

// let une = 10000;
// let noat = 1000;
// let niitUne = une + noat;
// console.log(niitUne);
// let message = "Hello, world!"; // String
// console.log(message);

// let age = 42; // Number
// console.log(age);

// let isStudent = true; // Boolean
// console.log(isStudent);

// let x; // undefined
// console.log(x);

// let n = null; // null
// console.log(n);

// let student = {
//   program: "HOP",
//   level: 1,
//   name: null,
//   isMale: false,
// };

// console.log(student);

// let studentList = [
//   {
//     program: "HOP",
//     level: 1,
//     name: null,
//     isMale: false,
//   },
//   {
//     program: "HOP",
//     level: 1,
//     name: "Orgil",
//     isMale: true,
//   },
//   {
//     program: "HOP",
//     level: 1,
//     name: "Bataa",
//     isMale: false,
//   },
// ];

// console.log(studentList);

// let studentsName = ["Orgil", "Naraa", "Bataa"];

// let person = {
//   firstName: "John",
//   lastName: "Doe",
// };

// console.log(person.firstName);
// console.log(person.lastName);

// let array = ["car", "apple", "pen", "bowl"];
// console.log(array[0]);
// console.log(array[1]);

// const textOne = "1";
// const numberOne = 1;

// console.log(typeof textOne);
// console.log(typeof numberOne);

// const textTwo = "2";
// const numberTwo = 2;

// console.log(numberTwo + textTwo, typeof (numberTwo + textTwo));
// console.log(numberTwo / textTwo, typeof (numberTwo / textTwo));

// const textThree = "Hello world";
// const numberThree = 23;
// console.log(textThree + numberThree, typeof (textThree + numberThree));
// console.log(textThree / numberThree, typeof (textThree / numberThree));

// const numberFour = 10;
// console.log(undefined / numberFour, typeof (undefined / numberFour));
// console.log(false / numberFour, typeof (false / numberFour));
// console.log(true / numberFour, typeof (true / numberFour));
// console.log(null / numberFour, typeof (null / numberFour));

// let a = 5;
// let b = 10;
// let c = 15;

// perimetr = a + b + c;

// console.log("bodlogo-1: ugugdsun gurvaljingiin perimetr-iig ol:");
// console.log("bodlogo-1 hariu: ","Perimetr=", perimetr);

// let sum = 0;
// const numbers = [1, 3, 5, 7, 8.7];
// numbers.forEach(myFunction);
// function myFunction(item) {
//   sum += item;
// }
// console.log("bodlogo-2: buhel toonii niilberiig ol:");
// console.log("bodlogo-2 hariu: ", sum);

// urt = 10;
// urgun = 5;
// peri = 2 * (urt + urgun);
// talbai = urt * urgun;

// console.log("bodlogo-3: ugugdsun tegsh untsugtiin talbai ba perimetriig ol:");
// console.log("bodlogo-3 hariu: ","Perimetr=", peri,"Talbai=", talbai);

// let totalSec = 98;
// let sec = 0;
// let min = 0;

// sec = totalSec % 60;
// min = Math.floor(totalSec / 60);

// console.log("Bodlogo-4: ugugdsun sec iig min sec hurvuul: ", totalSec);
// console.log("Bodlogo-4 hariu: ", min + "min " + sec + "sec");

// let totalaSec = 1297;
// let seco = 0;
// let minu = 0;
// let hour = 0;

// seco = (totalaSec % 60) % 60;
// minu = Math.floor(totalaSec / 60);
// hour = Math.floor(totalaSec / 60 / 60);

// console.log(
//   "bodlogo-5: ugugdsun sec iig min sec tsag ruu hurvuul: ",
//   totalaSec
// );
// console.log("bodlogo-5 hariu: ", hour + "tsag " + minu + "min " + seco + "sec");

// let minut = 875;
// let secund = 88;
// let totalSecon = 0;

// totalSecon = minut * 60 + secund;

// console.log("bodlogo-6: ugugdsun min sec-iig secund ruu hurvuul:");
// console.log("bodlogo-6 hariu: ", totalSecon + "Sec");

// let tsag = 83;
// let minuto = 84;
// let secundo = 85;
// totalSecond = 0;

// totalSecond = tsag * 60 * 60 + minuto * 60 + secundo;

// console.log("bodlogo-7: ugugdsun tsag min sec-iig sucund ruu hurvuul:");
// console.log("bodlogo-7 hariu: ", totalSecond + "Sec");

//bodlogo-2   //9,3,2

// let toot1 = 2;
// let toot2 = 3;
// let toot3 = 9;

// if (toot1 < toot2 && toot1 < toot3) {
//   if (toot1 < toot3) {
//     console.log("Hamgiin baga too", toot1);
//   } else if (toot2 < toot1 && toot2 < toot3) {
//     console.log("Hamgiin baga too", toot1);
//   }
// } else if (toot3 < toot1 && toot3 < toot2) {
//   console.log("Hamgiin baga too", toot3);
// }

// console.log("Bodlogo-2: ugugdsun 3 toonii bagiig ol?");
// console.log("Bodlogo-2 hariu: ", "Hamgiin baga too:", toot1);

// //bodlogo-3

// q1 = 7;
// q2 = 1;
// q3 = 12;

// if (q3 > q2 && q3 > q1) {
//   console.log("Hamgiin ih too", q3);
// } else if (q1 > q2 && q3 > q2) {
//   console.log("hamgiin ih too", q3);
// }

// console.log("Bodlogo-3: ugugdsun 3 toonii ihiig ol?");
// console.log("Bodlogo-3 hariu: ", "Hamgiin ih too:", q3);

// //bodlogo-4

// let t1 = 2;
// let t2 = 9;
// let t3 = 4;

// let urjver = 1;

// if (t1 < 5) {
//   urjver = urjver * t1;
// }

// if (t2 < 5) {
//   urjver = urjver * t2;
// } else {
//   console.log("5-aas ih too baina.");
// }

// if (t3 < 5) {
//   urjver = urjver * t3;
// }

// urjver = t1 * t3;
// console.log("Urjver", urjver);

// console.log("Bodlogo-4: ugugdsun 3 toonii 5-aas baga toonuudiin urjveriig ol?");
// console.log("Bodlogo-4 hariu: ", "5-aas baga toonii urjver:", urjver);

// //bodlogo-5

// let w1 = 11,
//   w2 = 9,
//   w3 = 4,
//   w4 = 3,
//   urjvere = 1;

// if (w1 > 5) {
//   urjvere = urjvere * w1;
// }

// if (w2 > 5) {
//   urjvere = urjvere * w2;
// }

// if (w3 > 5) {
//   console.log("5-aas ih too baih yostoi.");
// } else {
//   console.log(w3, "5-aas baga too baina.");
// }

// if (w4 > 5) {
//   console.log("5-aas ih too baih yostoi.");
// } else {
//   console.log(w4, "5-aas baga too baina.");
// }

// urjvere = w1 * w2;

// console.log("Bodlogo-5: ugugdsun 4 toonii 5-aas ih toonuudiin urjveriig ol?");
// console.log("Bodlogo-5 hariu: ", "5-aas ih toonii urjver:", urjvere);

// //bodlogo-6

// sap = 9;

// if (sap === 12 || sap === 1 || sap === 2) {
//   console.log("Өвлийн улирал байна.");
// } else if (sap === 3 || sap === 4 || sap === 5) {
//   console.log("Хаврын улирал байна.");
// } else if (sap === 6 || sap === 7 || sap === 8) {
//   console.log("Зуны улирал байна.");
// } else if (sap === 9 || sap === 10 || sap === 11) {
//   console.log("Намрын улирал байна.");
// } else {
//   console.log("Таны оруулсан сарын тоо буруу байна.");
// }

// console.log("Bodlogo-6: Ugugdsun sar ali uliral we?");
// console.log("Bodlogo-6 hariu:", "Намрын улирал байна.");

// //bodlogo-1

// let m1 = 3,
//   m2 = 2,
//   m3 = 11,
//   m4 = 7;

// if (m1 % 2 === 0) {
//   console.log("Even");
// } else {
//   console.log("Odd");
// }
// if (m2 % 2 === 0) {
//   console.log("Even");
// } else {
//   console.log("Odd");
// }
// if (m3 % 2 === 0) {
//   console.log("Even");
// } else {
//   console.log("Odd");
// }
// if (m4 % 2 === 0) {
//   console.log("Even");
// } else {
//   console.log("Odd");
// }

// let nums = [3, 2, 11, 7];
// console.log("===============");

// for (let i = 0; i < 4; i++) {
//   if (nums[i] % 2 === 0) {
//     console.log("Even", nums[i]);
//   } else {
//     console.log("Odd", nums[i]);
//   }
// }

// let j = 0;

// while (j < 4) {
//   if (nums[j] % 2 === 0) {
//     console.log("Even", nums[j]);
//   } else {
//     console.log("Odd", nums[j]);
//   }
//   j++;
// }

// console.log("Bodlogo-1: Ugugdsun toonii tegsh sondgoig ol?");
// console.log("Bodlogo-1 hariu:", "Tegsh too:", m2, "Songdgoi too:", m1, m3, m4);

// //bodlogo-7

// let bat = 67;
// ochir = 59;
// dun = 0;

// const minNum = 1;
// const maxNum = 59;

// if (dun <= 59) {
//   console.log("mash muu");
// }

// miniNum = 60;
// maxiNum = 69;

// if (dun <= 69) {
//   console.log("muu");
// }

// minimNum = 70;
// maximNum = 79;

// if (dun <= 79) {
//   console.log("dund");
// }

// minimuNum = 80;
// maximuNum = 89;

// if (dun <= 89) {
//   console.log("sain");
// }

// minimumNum = 90;
// maximumNum = 100;

// if (dun <= 100) {
//   console.log("onts");
// }

// console.log("Bodlogo-7: Suragchiin dung dugne?");
// console.log("Bodlogo-7 hariu:", bat, ochir);

//bodlogo-1

for (let a = 0; a <= 100; a ++){
if(a % 2 ==0){console.log(a)}
}

//bodlogo-2

for (let b = 1; b <= 100; b ++) {
if(b % 2 ==1){console.log(b)} 
}

//bodlogo-3

let ee = 1;
for(let dd = 1; dd < 200; dd ++){
if(dd % 2 === 0)
{ee *= dd

}
} console.log(ee)


//bodlogo-4

let e = 0;
for(let d = 1; d < 200; d ++){
if(d % 2 === 1)
  {e += d
}
} console.log(e)

//bodlogo-8

let f = 1234;
let g = 0;
let h = 0;
count = 0;

while(f !== 0){
  g = f % 10;
  h = h + g;
  f = (f - g) / 10;
  console.log("==============")
  count ++
  console.log("DIG:", g);
  console.log("H:", h);
  console.log("F:", f);
  console.log("COUNT:", count)
}

const arr = [1, 2, 3, 4, 5];
console.log("ORIGINAL:", arr)
for(let = r = 0; r < arr.length; r ++){
  arr[r] = arr[r] * 2;
}
  console.log("changed:", arr);
  console.log("===============")
